# SPDX-License-Identifier: GPL-2.0

# Enable available and selected Clang AutoFDO features.

CFLAGS_AUTOFDO_CLANG := -fdebug-info-for-profiling -mllvm -enable-fs-discriminator=true -mllvm -improved-fs-discriminator=true

ifndef CONFIG_DEBUG_INFO
  CFLAGS_AUTOFDO_CLANG += -gmlt
endif

ifdef CLANG_AUTOFDO_PROFILE
  CFLAGS_AUTOFDO_CLANG += -fprofile-sample-use=$(CLANG_AUTOFDO_PROFILE) -ffunction-sections
  CFLAGS_AUTOFDO_CLANG += -fsplit-machine-functions
ifdef CONFIG_AUTOFDO_PROFILE_ACCURATE
  CFLAGS_AUTOFDO_CLANG += -fprofile-sample-accurate
endif
endif

ifdef CONFIG_LTO_CLANG_THIN
  _ldflags_autofdo := --mllvm=-enable-fs-discriminator=true --mllvm=-improved-fs-discriminator=true -plugin-opt=thinlto
  _ldflags_autofdo += -plugin-opt=-split-machine-functions
  ifdef CLANG_AUTOFDO_PROFILE
    _ldflags_autofdo += --lto-sample-profile=$(CLANG_AUTOFDO_PROFILE)
  endif
  # TODO: change LDFLAGS_vmlinux to KBUILD_LDFLAGS when kernel modules
  # are supported.
  LDFLAGS_vmlinux += $(_ldflags_autofdo)
endif

export CFLAGS_AUTOFDO_CLANG
